version: '3.8'


services:
  ms_order-dev:
    build:
      context: .
      target: development
    container_name: ms_order
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8002 --reload 
    env_file:
        - .env.dev
    volumes:
      - .:/app
    ports:
      - 8002:8002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - my_network



networks:
  my_network:
    external: true # ?
