"""first migrate, order and irder_item

Revision ID: 5ada594929e0
Revises: 
Create Date: 2025-05-05 21:18:03.822013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ada594929e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BASKET', 'PENDING', 'READY', 'COMPLETED', 'CANCELLED', name='orderstatusenum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ms_order'
    )
    op.create_index(op.f('ix_ms_order_orders_user_id'), 'orders', ['user_id'], unique=False, schema='ms_order')
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ms_order.orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ms_order'
    )
    op.create_index(op.f('ix_ms_order_order_items_dish_id'), 'order_items', ['dish_id'], unique=False, schema='ms_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ms_order_order_items_dish_id'), table_name='order_items', schema='ms_order')
    op.drop_table('order_items', schema='ms_order')
    op.drop_index(op.f('ix_ms_order_orders_user_id'), table_name='orders', schema='ms_order')
    op.drop_table('orders', schema='ms_order')
    # ### end Alembic commands ###
