"""update dish_name and unit_price

Revision ID: d7feec593639
Revises: 5ada594929e0
Create Date: 2025-05-10 20:11:28.046799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7feec593639'
down_revision: Union[str, None] = '5ada594929e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'dish_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               schema='ms_order')
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=True,
               schema='ms_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(),
               nullable=False,
               schema='ms_order')
    op.alter_column('order_items', 'dish_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               schema='ms_order')
    # ### end Alembic commands ###
